-- Mapzilla Balanced - Mountains to delta. Based on Mapzilla (tools/build.py output), edited by hand since.
--
-- The stock temperate generator pointed at our own node tree: the stock graph
-- with one river laid out by our scripted node, with the mountains and the sea
-- placed around it in the layout the Layout dropdown asks for.
-- The stock sliders are untouched and still work.
function data()
return { 
		nodeTree = "mapzilla_balanced_temperate.tree",
		climate = "::/climates/temperate/temperate.clima",
		desc = { 
			cargoTypeSet = { 
				cargoClassesExcluded = { },
				cargoClassesIncluded = { },
				cargoTypesExcluded = { },
				cargoTypesIncluded = { },
			},
			name = _("Mapzilla Balanced - Mountains to delta"),
		},
		editorOnly = false,
		order = 90,
		params = {
			{
				defaultIndex = 1,
				images = { },
				key = "mz_layout",
				name = _("Layout"),
				tags = { },
				tooltip = _("Where the mountains and the sea are."),
				uiType = "ComboBox",
				valueIndices = { },
				values = {
					_("Random"),
					_("Single shore"),
					_("Island"),
					_("Inland sea"),
					_("Isthmus"),
					_("Strait"),
					_("Peninsula"),
					_("Bay"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{
				defaultIndex = 3,
				images = { },
				key = "mz_coast",
				name = _("Coastline"),
				tags = { },
				tooltip = _("How far the coastline wanders in and out of a straight line."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Straight"),
					_("Gentle"),
					_("Medium"),
					_("Rugged"),
					_("Wild"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{
				defaultIndex = 3,
				images = { },
				key = "mz_islands",
				name = _("Islands"),
				tags = { },
				tooltip = _("How many islands lie off the coast."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Few"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{
				defaultIndex = 2,
				images = { },
				key = "mz_axis",
				name = _("Orientation"),
				tags = { },
				tooltip = _("Which side of the map the layout runs along. A square map looks the same either way."),
				uiType = "ComboBox",
				valueIndices = { },
				values = {
					_("Random"),
					_("Long side"),
					_("Short side"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "oceans",
				name = _("Lakes"),
				tags = { },
				tooltip = _("Adjust the number of lakes on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "water",
				name = _("Rivers"),
				tags = { },
				tooltip = _("Adjust the number of rivers on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "mountains",
				name = _("Mountains"),
				tags = { },
				tooltip = _("Adjust the number and height of mountains on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
		},
		previewSeed = "yQKiK",
		updateScript = { 
			fileName = "",
			params = { },
		},
	}
end
